engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 30
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-67
ratings:
  paths:
    - '**.rb'
exclude_paths:
  - spec/**/*
