require: rubocop-rspec

ClassLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
