require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Bundler/GemFilename:
  EnforcedStyle: gems.rb

Layout/LineLength:
  Max: 120

Lint/FloatComparison:
  Enabled: false

Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Naming/VariableNumber:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
