name: ci

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2']
    name: Run tests on on Ruby ${{matrix.ruby}}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
    - run: bundle install
    - run: bundle exec rspec
    - run: bundle exec rubocop
