name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    name: Run tests on on Ruby ${{ matrix.ruby }}

    strategy:
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2"]

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run test suite
        run: bundle exec rspec

      - name: Run linter
        run: bundle exec rubocop
